DROP TRIGGER IF EXISTS tags_au;
DROP TRIGGER IF EXISTS tags_ad;
DROP TRIGGER IF EXISTS tags_ai;
DROP TABLE IF EXISTS tags_fts;

DROP TRIGGER IF EXISTS people_au;
DROP TRIGGER IF EXISTS people_ad;
DROP TRIGGER IF EXISTS people_ai;
DROP TABLE IF EXISTS people_fts;

DROP TRIGGER IF EXISTS videos_au;
DROP TRIGGER IF EXISTS videos_ad;
DROP TRIGGER IF EXISTS videos_ai;
DROP TABLE IF EXISTS videos_fts;

DROP TABLE IF EXISTS video_metadata;
DROP TABLE IF EXISTS video_tags;
DROP TABLE IF EXISTS video_people;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS videos;
